# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
